# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tally < Formula
  desc "Tally up source files in a directory"
  homepage "https://github.com/ahmedsaheed/tally"
  version "0.1.1"

  on_macos do
    on_intel do
      url "http://github.com/ahmedsaheed/tally/releases/v0.1.1/tally_Darwin_x86_64.tar.gz"
      sha256 "a489b61e43bfa0c539e17a81569a20e1bf1b1d331bd422d71757024c25bca980"

      def install
        bin.install "tally"
      end
    end
    on_arm do
      url "http://github.com/ahmedsaheed/tally/releases/v0.1.1/tally_Darwin_arm64.tar.gz"
      sha256 "e2e75d0e506a885f0ce34954974a3bac9acd8a89d5080472e18299bb0f25058b"

      def install
        bin.install "tally"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "http://github.com/ahmedsaheed/tally/releases/v0.1.1/tally_Linux_x86_64.tar.gz"
        sha256 "419cd4b3cac81fed5dba4ad02eb2a059014d64f9b04efa863ce4a12eafb5fe41"

        def install
          bin.install "tally"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "http://github.com/ahmedsaheed/tally/releases/v0.1.1/tally_Linux_arm64.tar.gz"
        sha256 "7a65839606e02741dbcddf1e180b75904ccb8efeb2172a2504d5e517529c313b"

        def install
          bin.install "tally"
        end
      end
    end
  end
end
